[package]
name = "github_notification_pusher"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
dotenvy = "0.15.7"
env_logger = "0.11.6"
futures-util = "0.3.31"
log = "0.4.25"

[lib]
name = "github_notification_pusher"
path = "src/lib.rs"
